name: Enhancement Request
description: Create a request to help us enhance a particular feature
title: "Your issue title here"
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the enhancement you'd like to see implemented.
      options:
      - label: I have searched the existing issues.
        required: true
  - type: textarea
    id: related-feature
    attributes:
      label: Please describe the enhancement you have in mind and explain what the current shortcomings are?
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: enhancement-proposal
    attributes:
      label: How would you imagine the implementation of the enhancement?
      description: A clear and concise description of the changes you have in mind.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Are there any labels you wish to add?
      description: Please search labels and identify those related to your enhancement.
      options:
      - label: I have added the relevant labels to the enhancement request.
        required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered:"
      description: A clear and concise description of any alternative solutions you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context:"
      description: Add any other context or screenshots about the enhancement request here.
    validations:
      required: false
