name: 🚀 Release Trigger

on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        description: "Create Release Draft"
        required: false
        default: true

jobs:
  call-release-trigger:
    uses: ${{ vars.WORKFLOW_REPO }}/.github/workflows/release_trigger.yml@${{ vars.WORKFLOW_CHECKOUT }}
    with:
      draft: ${{ inputs.draft }}
    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
      email: ${{ secrets.CI_EMAIL }}
      user: ${{ secrets.CI_USER }}