name: Initial Release Trigger
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      draft:
        type: boolean
      release_overwrite:
        type: string

    secrets:
      token:
        required: true
      email:
        required: true
      user:
        required: true

env:
  LABEL_DELIMITTER: ", "
  GH_TOKEN: ${{ secrets.token || secrets.YNPUT_BOT_TOKEN}}
  GH_USER: ${{ secrets.user || secrets.CI_USER }}
  GH_EMAIL: ${{ secrets.email || secrets.CI_EMAIL }}
  INIT_VERSION: "0.1.0"
  RELEASE_NAME: ${{ inputs.name || '' }}
  DRAFT: ${{ inputs.draft }}
  ARTIFACT_NAME: "${{ vars.PROJECT_NAME }}-package"
  PROJECT_NAME: "${{ vars.PROJECT_NAME }}"

jobs:
  verify-latest-release:
    uses: ynput/ops-repo-automation/.github/workflows/verify_latest_release.yml@refactor-release-workflow-structure
    with:
      repo: ${{ github.repository }}
      expect_release: false
    secrets:
      gh_token: ${{ secrets.token }}


  verify-repo-secrets:
    uses: ynput/ops-repo-automation/.github/workflows/verify_secrets.yml@refactor-release-workflow-structure
    with:
      repo: ${{ github.repository }}
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }}


  verify-repo-vars:
    uses: ynput/ops-repo-automation/.github/workflows/verify_variables.yml@refactor-release-workflow-structure
    with:
      variables: "MAIN_BRANCH,MINOR_BUMP_LABEL,PATCH_BUMP_LABEL,PROJECT_NAME"
      repo: ${{ github.repository }}
    secrets:
      gh_token: ${{ secrets.token }}


  merge-to-main:
    runs-on: ubuntu-latest
    needs:
      - verify-latest-release
      - verify-repo-secrets
      - verify-repo-vars

    steps:
      - name: ⬇️ Checkout ${{ vars.MAIN_BRANCH }}
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.MAIN_BRANCH }}
          fetch-depth: 0

      - name: 🔑 Set Bot Authentication
        run: |
          git config --global user.name "${{ env.GH_USER }}"
          git config --global user.email "${{ env.GH_EMAIL }}"

      - name: 🔀 Merge ${{ github.ref_name }} -> ${{ vars.MAIN_BRANCH }}
        run: |
          git pull origin ${{ github.ref_name }}
          git merge --no-ff origin/${{ github.ref_name }} -m "[Automated] Merged ${{ github.ref_name }} -> ${{ vars.MAIN_BRANCH }}"

      # TODO implement this using gh command
      - name: 🔏 Push to protected main branch
        uses: CasperWA/push-protected@v2.15.0
        with:
          token: ${{ env.GH_TOKEN }}
          branch: ${{ vars.MAIN_BRANCH }}
          tags: false
          unprotect_reviews: false


  build-from-main:
    runs-on: ubuntu-latest
    needs:
      - merge-to-main
    env:
      OUTPUT_DIR: "artifact"
    outputs:
      artifact_file: ${{ steps.create-artifact.outputs.file_name }}

    steps:
      - name: ⬇️ Checkout ${{ vars.MAIN_BRANCH }}
        uses: actions/checkout@v4
        with:
          ref: ${{ vars.MAIN_BRANCH }}
          fetch-depth: 0

      - name: Update package.py version to ${{ env.INIT_VERSION }}
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ env.INIT_VERSION }}\"/" package.py
          sed -i "s/^name = \".*\"/name = \"${{ env.PROJECT_NAME }}\"/" package.py

      - name: Create artifacts
        id: create-artifact
        run: |
          python create_package.py --output ${{ env.OUTPUT_DIR }}
          echo "file_name=${{ env.PROJECT_NAME }}-${{ env.INIT_VERSION }}.zip" >> $GITHUB_OUTPUT

      - name: 🔑 Set Bot Authentication
        run: |
          git config --global user.name "${{ env.GH_USER }}"
          git config --global user.email "${{ env.GH_EMAIL }}"

      - name: Add generated files from ${{ vars.MAIN_BRANCH }}
        run: |
          git add . -- ':!${{ env.OUTPUT_DIR }}/${{ steps.create-artifact.outputs.file_name }}'
          if git diff --cached --exit-code > /dev/null; then
            echo "No changes to commit"
          else
            git commit -m "[Automated] Add generated package files from ${{ vars.MAIN_BRANCH }}"
          fi

          git tag -a ${{ env.INIT_VERSION }} -m "[Automated] Release version ${{ env.INIT_VERSION }}"

      - name: 🔏 Push to protected ${{ vars.MAIN_BRANCH }} branch
        uses: CasperWA/push-protected@v2.16.0
        with:
          token: ${{ env.GH_TOKEN }}
          branch: ${{ vars.MAIN_BRANCH }}
          tags: false
          unprotect_reviews: false

      - name: 🔼 Upload zip artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.OUTPUT_DIR }}/${{ steps.create-artifact.outputs.file_name }}


  update-develop:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: "artifact"
    needs:
      - build-from-main

    steps:
      - name: ⬇️ Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: 🔀 Merge ${{ vars.MAIN_BRANCH }} -> ${{ github.ref_name }}
        run: |
          git pull origin ${{ vars.MAIN_BRANCH }}
          git merge --no-ff origin/${{ vars.MAIN_BRANCH }} -m "[Automated] Merged ${{ vars.MAIN_BRANCH }} -> ${{ github.ref_name }}"

      - name: Read version from package.py
        id: package-version
        run: |
          version=$(sed -n 's/^version *= *"\(.*\)"/\1/p' package.py)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update package version for ${{ github.ref_name }}
        id: develop-version
        run: |
          echo "develop_version=${{ env.INIT_VERSION }}-dev" >> $GITHUB_OUTPUT

      - name: Update package version for 
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ steps.develop-version.outputs.develop_version }}\"/" package.py

      - name: Create artifacts
        id: create-artifact
        run: |
          python create_package.py --output ${{ env.OUTPUT_DIR }}

      - name: 🔑 Set Bot Authentication
        run: |
          git config --global user.email "${{ env.GH_EMAIL }}"
          git config --global user.name "${{ env.GH_USER }}"

      - name: Update package.py version to ${{ steps.develop-version.outputs.develop_version }}
        if: ${{ steps.package-version.outputs.version != steps.develop-version.outputs.develop_version }}
        run: |
          git add . -- ':!${{ env.OUTPUT_DIR }}/${{ steps.create-artifact.outputs.file_name }}'
          git commit -m "[Automated] Update version in package.py for develop"

      - name: 🔏 Push to protected ${{ github.ref_name }} branch
        uses: CasperWA/push-protected@v2.16.0
        with:
          token: ${{ env.GH_TOKEN }}
          branch: ${{ github.ref_name }}
          tags: false
          unprotect_reviews: false


  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-from-main

    steps:
      - name: 🔽 Download zip artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          
      - name: 🚀 Create Github Release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ vars.MAIN_BRANCH }}
          tag: "${{ env.INIT_VERSION }}"
          generateReleaseNotes: true
          artifacts: ${{ needs.build-from-main.outputs.artifact_file }}
          token: ${{ env.GH_TOKEN }}
          draft: true


  verify-release:
    runs-on: ubuntu-latest
    needs:
      - create-release

    steps:
      - name: Fetch Latest Release Draft
        id: fetch-latest-release-draft
        run: |
          current_release_name="$(gh release list --repo ${{ github.repository }} --json isDraft,name,createdAt --jq '[.[] | select(.isDraft == true)] | sort_by(.createdAt) | reverse | .[0].name')"
          echo "current_release_name=$current_release_name" >> $GITHUB_OUTPUT

      - name: 🔍 Verify Release-Draft Name
        id: check-release-tag
        env:
          latest_release_draft: ${{ steps.fetch-latest-release-draft.outputs.current_release_name }}
        run: |
          if [ "${{ env.INIT_VERSION }}" == "${{ env.latest_release_draft }}" ]; then
            echo "::notice::Success, release-draft found with the expected name ${{ env.INIT_VERSION }}."
            exit 0
          fi

          echo "::error::Expected tag ${{ env.INIT_VERSION }}, but found ${{ env.latest_release_draft }}."
          exit 1