name: Initial Release Trigger
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      draft:
        type: boolean
      release_overwrite:
        type: string

    secrets:
      token:
        required: true
      email:
        required: true
      user:
        required: true

env:
  GH_TOKEN: ${{ secrets.token || secrets.YNPUT_BOT_TOKEN}}
  GH_USER: ${{ secrets.user || secrets.CI_USER }}
  GH_EMAIL: ${{ secrets.email || secrets.CI_EMAIL }}
  RELEASE_NAME: ${{ inputs.name || '' }}
  DRAFT: ${{ inputs.draft }}
  ARTIFACT_NAME: "${{ vars.PROJECT_NAME }}-package"
  PROJECT_NAME: "${{ vars.PROJECT_NAME }}"

jobs:
  verify-latest-release:
    uses: ynput/ops-repo-automation/.github/workflows/verify_latest_release.yml@main
    with:
      repo: ${{ github.repository }}
      expect_release: false
    secrets:
      gh_token: ${{ secrets.token }}


  verify-repo-secrets:
    uses: ynput/ops-repo-automation/.github/workflows/verify_secrets.yml@main
    with:
      repo: ${{ github.repository }}
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }}


  verify-repo-vars:
    uses: ynput/ops-repo-automation/.github/workflows/verify_variables.yml@main
    with:
      variables: "MAIN_BRANCH,MINOR_BUMP_LABEL,PATCH_BUMP_LABEL,PROJECT_NAME"
      repo: ${{ github.repository }}
    secrets:
      gh_token: ${{ secrets.token }}


  merge-to-main:
    needs:
      - verify-latest-release
      - verify-repo-secrets
      - verify-repo-vars

    uses: ynput/ops-repo-automation/.github/workflows/merge_branch.yml@main
    with:
      repo: ${{ github.repository }}
      checkout_branch: ${{ vars.MAIN_BRANCH }}
      merge_from_branch: ${{ github.ref_name }}
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }}


  build-from-main:
    needs:
      - merge-to-main

    uses: ynput/ops-repo-automation/.github/workflows/build_from_branch.yml@main
    with:
      repo:   ${{ github.repository }}
      branch_name: ${{ vars.MAIN_BRANCH }}
      project_name: ${{ vars.PROJECT_NAME }}
      artifact_name: "${{ vars.PROJECT_NAME }}-package"
      next_version: "${{ inputs.release_overwrite }}"
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }}


  update-develop:
    needs:
      - build-from-main

    uses: ynput/ops-repo-automation/.github/workflows/update_branch.yml@main
    with:
      repo: ${{ github.repository }}
      checkout_branch: ${{ github.ref_name }}
      update_from_branch: ${{ vars.MAIN_BRANCH }}
      next_version: ${{ inputs.release_overwrite }}
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }}


  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-from-main

    steps:
      - name: 🔽 Download zip artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          
      - name: 🚀 Create Github Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.release_overwrite }}
          generateReleaseNotes: true
          artifacts: ${{ needs.build-from-main.outputs.artifact_file }}
          token: ${{ env.GH_TOKEN }}
          draft: ${{ inputs.draft }}


  verify-release:
    needs:
      - create-release

    uses: ynput/ops-repo-automation/.github/workflows/verify_created_release.yml@main
    with:
      repo: ${{ github.repository }}
      expected_release_name: "${{ inputs.release_overwrite }}"
      draft_release: ${{ inputs.draft }}
    secrets:
      gh_token: ${{ secrets.token }}

    # TODO verify tag position
