name: Initial Release Trigger
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      draft:
        type: boolean
      release_overwrite:
        type: string

    secrets:
      token:
        required: true
      email:
        required: true
      user:
        required: true

env:
  LABEL_DELIMITTER: ", "
  GH_TOKEN: ${{ secrets.token || secrets.YNPUT_BOT_TOKEN}}
  GH_USER: ${{ secrets.user || secrets.CI_USER }}
  GH_EMAIL: ${{ secrets.email || secrets.CI_EMAIL }}
  INIT_VERSION: "0.1.0"
  RELEASE_NAME: ${{ inputs.name || '' }}
  DRAFT: ${{ inputs.draft }}
  ARTIFACT_NAME: "${{ vars.PROJECT_NAME }}-package"
  PROJECT_NAME: "${{ vars.PROJECT_NAME }}"

jobs:
  verify-latest-release:
    uses: ynput/ops-repo-automation/.github/workflows/verify_latest_release.yml@refactor-release-workflow-structure
    with:
      repo: ${{ github.repository }}
      expect_release: false
    secrets:
      gh_token: ${{ secrets.token }}


  verify-repo-secrets:
    uses: ynput/ops-repo-automation/.github/workflows/verify_secrets.yml@refactor-release-workflow-structure
    with:
      repo: ${{ github.repository }}
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }}


  verify-repo-vars:
    uses: ynput/ops-repo-automation/.github/workflows/verify_variables.yml@refactor-release-workflow-structure
    with:
      variables: "MAIN_BRANCH,MINOR_BUMP_LABEL,PATCH_BUMP_LABEL,PROJECT_NAME"
      repo: ${{ github.repository }}
    secrets:
      gh_token: ${{ secrets.token }}


  merge-to-main:
    needs:
      - verify-latest-release
      - verify-repo-secrets
      - verify-repo-vars

    uses: ynput/ops-repo-automation/.github/workflows/merge_branch.yml@refactor-release-workflow-structure
    with:
      repo: ${{ github.repository }}
      checkout_branch: ${{ vars.MAIN_BRANCH }}
      merge_from_branch: ${{ github.ref_name }}
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }}


  build-from-main:
    needs:
      - merge-to-main

    uses: ynput/ops-repo-automation/.github/workflows/build_from_branch.yml@refactor-release-workflow-structure
    with:
      # repo:   ${{ github.repository }}
      branch_name: ${{ vars.MAIN_BRANCH }}
      project_name: ${{ vars.PROJECT_NAME }}
      artifact_name: "${{ vars.PROJECT_NAME }}-package"
      next_version: "${{ inputs.release_overwrite }}"
    secrets:
      gh_token: ${{ secrets.token }}
      gh_user: ${{ secrets.user }}
      gh_email: ${{ secrets.email }} 


  update-develop:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: "artifact"
    needs:
      - build-from-main

    steps:
      - name: ⬇️ Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: 🔀 Merge ${{ vars.MAIN_BRANCH }} -> ${{ github.ref_name }}
        run: |
          git pull origin ${{ vars.MAIN_BRANCH }}
          git merge --no-ff origin/${{ vars.MAIN_BRANCH }} -m "[Automated] Merged ${{ vars.MAIN_BRANCH }} -> ${{ github.ref_name }}"

      - name: Read version from package.py
        id: package-version
        run: |
          version=$(sed -n 's/^version *= *"\(.*\)"/\1/p' package.py)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update package version for ${{ github.ref_name }}
        id: develop-version
        run: |
          echo "develop_version=${{ env.INIT_VERSION }}-dev" >> $GITHUB_OUTPUT

      - name: Update package version for 
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ steps.develop-version.outputs.develop_version }}\"/" package.py

      - name: Create artifacts
        id: create-artifact
        run: |
          python create_package.py --output ${{ env.OUTPUT_DIR }}

      - name: 🔑 Set Bot Authentication
        run: |
          git config --global user.email "${{ env.GH_EMAIL }}"
          git config --global user.name "${{ env.GH_USER }}"

      - name: Update package.py version to ${{ steps.develop-version.outputs.develop_version }}
        if: ${{ steps.package-version.outputs.version != steps.develop-version.outputs.develop_version }}
        run: |
          git add . -- ':!${{ env.OUTPUT_DIR }}/${{ steps.create-artifact.outputs.file_name }}'
          git commit -m "[Automated] Update version in package.py for develop"

      - name: 🔏 Push to protected ${{ github.ref_name }} branch
        uses: CasperWA/push-protected@v2.16.0
        with:
          token: ${{ env.GH_TOKEN }}
          branch: ${{ github.ref_name }}
          tags: false
          unprotect_reviews: false


  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-from-main

    steps:
      - name: 🔽 Download zip artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          
      - name: 🚀 Create Github Release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ vars.MAIN_BRANCH }}
          tag: "${{ env.INIT_VERSION }}"
          generateReleaseNotes: true
          artifacts: ${{ needs.build-from-main.outputs.artifact_file }}
          token: ${{ env.GH_TOKEN }}
          draft: true


  verify-release:
    needs:
      - create-release

    uses: ynput/ops-repo-automation/.github/workflows/verify_created_release.yml@refactor-release-workflow-structure
    with:
      repo: ${{ github.repository }}
      expected_release_name: "${{ inputs.release_overwrite }}"
      draft_release: ${{ inputs.draft }}
    secrets:
      gh_token: ${{ secrets.token }}

    # TODO verify tag position
