name: Auto assign pr
on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      project_url:
        type: string
        required: true
      pull_request_number:
        type: number
        required: true

    secrets:
      token:
        required: true

jobs:
  auto-assign-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR to project
        env:
          GH_TOKEN: ${{ secrets.token }}
          PROJECT_URL: ${{ inputs.project_url }}
        run: |
          gh project item-add "${{ env.PROJECT_URL }}" --item "$(gh pr view ${{ inputs.pull_request_number }} --json id -q '.id')" --repo "${{ inputs.repo }}"
