name: Auto assign pr
on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      project_id:
        type: number
        required: true
      pull_request_number:
        type: number
        required: true
    secrets:
      token:
        required: true

# INFO fallback to default `github.token` is required for PRs from folks
# INFO organization secrets won't be available to forks
env:
  GH_TOKEN: ${{ secrets.token || github.token }}

jobs:
  auto-assign-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Token
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "GH_TOKEN is not set"
            exit 1
          else
            echo "GH_TOKEN is set"
          fi

      - name: Validate PR Source
        if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
        run: |
            echo "::Warning::This workflow cannot handle PRs from forks."
            exit 0

      - name: Assign PR to project
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        run: |
          gh project item-add ${{ inputs.project_id }} --owner ynput --url "$(gh pr view ${{ inputs.pull_request_number }} --json url -q '.url' --repo '${{ inputs.repo }}')"
