name: ⬆️ Push Caller Workflow

on:
  workflow_dispatch:
    inputs:
      repo_group:
        description: Repository group to batch process
        type: string
        required: true
    #   target_branch:
    #     description: Branch the workflow should be pushed to
    #     type: string
    #     required: true
    #   caller_workflow_name:
    #     description: 
    #     type: string
    #     required: true

env:
  GH_TOKEN: ${{ secrets.YNPUT_BOT_TOKEN }}

jobs:
  get-repos:
    runs-on: ubuntu-latest
    outputs:
        repo_matrix: ${{ steps.build-matrix.outputs.matrix }}

    steps:
      # TODO Get repos sorted by topics from organization
      - name: Build matrix
        id: build-matrix
        run: |
          echo "matrix=['ayon-addon-action-testing', 'ayon-sample']" >> $GITHUB_OUTPUT

  update-repos:
    needs:
        - get-repos
    runs-on: ubuntu-latest
    strategy:
        matrix: ${{ fromJson(needs.get-repos.outputs.repo_matrix) }}

    steps:
      - name: Process Matrix Value
        run: |
          echo "Processing value: ${{ matrix.value }}"

          if ! gh repo view "ynput/$repo" &>/dev/null; then
            echo "::warning::Repository $repo was not found."
            continue
          fi
        # skip repo and output warning in doesn't exist
    