name: Query latest release

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: false

    secrets:
      gh_token:
        required: true

    outputs:
        id:
          description: Release ID
          value: ${{ jobs.latest-release.outputs.id }}
        name:
          description: Release name
          value: ${{ jobs.latest-release.outputs.name }}
        tag:
          description: Release ID
          value: ${{ jobs.latest-release.outputs.tag }}
        date_created:
          description: Release name
          value: ${{ jobs.latest-release.outputs.date_created }}
        date_published:
          description: Release ID
          value: ${{ jobs.latest-release.outputs.date_published }}
        draft:
          description: Release name
          value: ${{ jobs.latest-release.outputs.draft }}
        pre_release:
          description: Release name
          value: ${{ jobs.latest-release.outputs.pre_release }}

env:
  GH_REPO : ${{ inputs.repo || github.repository }}
  GH_TOKEN: ${{ secrets.gh_token || false }}

jobs:
  latest-release:

    runs-on: ubuntu-latest

    outputs:
        id: ${{ steps.latest-release.outputs.id }}
        name: ${{ steps.latest-release.outputs.name }}
        tag: ${{ steps.latest-release.outputs.tag }}
        date_created: ${{ steps.latest-release.outputs.date_created }}
        date_published: ${{ steps.latest-release.outputs.date_published }}
        draft: ${{ steps.latest-release.outputs.draft }}
        pre_release: ${{ steps.latest-release.outputs.pre_release}}

    steps:
      - name: Get latest release
        id: latest-release
        run: |
            declare -A release_option_map=(
                ["id"]="id"
                ["createdAt"]="date_created"
                ["publishedAt"]="date_published"
                ["tagName"]="tag"
                ["name"]="name"
                ["isDraft"]="draft"
                ["isPrerelease"]="pre_release"
            )

            key_list=$(IFS=,; echo "${!release_option_map[*]}")
            release=$(gh release view --repo ${{ env.GH_REPO }} --json $key_list || true)

            for key in "${!release_option_map[@]}"; do
                value=$(echo "$release" | jq -r ".$key")
                echo "${release_option_map[$key]}=$value" >> $GITHUB_OUTPUT
            done

      - name: Show release data
        run: |
            echo "Release ID: ${{ steps.latest-release.outputs.id }}"
            echo "Release Name: ${{ steps.latest-release.outputs.name }}"
            echo "Tag Name: ${{ steps.latest-release.outputs.tag }}"
            echo "Date Created: ${{ steps.latest-release.outputs.date_created }}"
            echo "Date Published: ${{ steps.latest-release.outputs.date_published }}"
            echo "Draft Status: ${{ steps.latest-release.outputs.draft }}"
            echo "Pre-release Status: ${{ steps.latest-release.outputs.pre_release }}"
