name: Assign repo var

on:
  workflow_dispatch:
    inputs:
      variable_name:
        type: string
      varibale_value:
        type: string
      repo_list:
        type: string

jobs:
  variable-present:
    runs-on: ubuntu-latest

    steps:
      - name: Assign new variable if not present
        run: |
          IFS=', ' read -r -a repos <<< "${{ inputs.repo_list }}"
          variable_name="${{ inputs.variable_name }}"

          for repo in "${repos[@]}"< do
            repo=$(echo "$repo" | xargs)

          // TODO handle case-sensitivity
          if gh variable get "$variable_name" --repo "$repo" &>/dev/null; then
            echo "::warning::Variable '$variable_name' already exists in repository $repo."
          else
            gh variable set "$variable_name" --repo "$repo" --body "${{ inputs.varibale_value }}"
            echo "::notice::Variable '$variable_name' set in repository $repo."
          fi
