name: Update Branch

on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      checkout_branch:
        type: string
        required: true
      update_from_branch:
        type: string
        required: true
      next_version:
        type: string
        required: true
    secrets:
      gh_token:
        required: true
      gh_user:
        required: true
      gh_email:
        required: true

env:
    GH_TOKEN: ${{ secrets.gh_token }}
    OUTPUT_DIR: "artifact"
    NEXT_PACKAGE_VERSION: "${{ inputs.next_version }}+dev"

jobs:
  update-branch:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout ${{ inputs.checkout_branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_branch }}

      - name: 🔀 Merge ${{ inputs.update_from_branch }} -> ${{ inputs.checkout_branch }}
        run: |
          git pull origin ${{ inputs.update_from_branch }}
          git merge --no-ff origin/${{ inputs.update_from_branch }} -m "[Automated] Merged ${{ inputs.update_from_branch }} -> ${{ inputs.checkout_branch }}"

      - name: Read version from package.py
        id: package-version
        run: |
          version=$(sed -n 's/^version *= *"\(.*\)"/\1/p' package.py)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Update package version for ${{ inputs.checkout_branch }} to ${{ env.NEXT_PACKAGE_VERSION }}
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ env.NEXT_PACKAGE_VERSION }}\"/" package.py

      - name: Create artifacts
        id: create-artifact
        run: |
          python create_package.py --output ${{ env.OUTPUT_DIR }}

      - name: 🔑 Set Bot Authentication
        run: |
          git config --global user.name "${{ secrets.gh_user }}"
          git config --global user.email "${{ secrets.gh_email }}"

      - name: Commit generated files
        if: ${{ steps.package-version.outputs.version != env.NEXT_PACKAGE_VERSION }}
        run: |
          git add . -- ':!${{ env.OUTPUT_DIR }}/${{ steps.create-artifact.outputs.file_name }}'
          git commit -m "[Automated] Update version in package.py for develop"

      - name: 🔏 Push to protected ${{ github.ref_name }} branch
        uses: CasperWA/push-protected@v2.16.0
        with:
          token: ${{ env.GH_TOKEN }}
          branch: ${{ github.ref_name }}
          tags: false
          unprotect_reviews: false