name: Validate PR labels
on:
  workflow_call:
    inputs:
      repo:
        type: string
        required: true
      pull_request_number:
        type: number
        required: true
      query_prefix:
        type: string
        required: true
        default: "type: "

    secrets:
      token:
        required: true

jobs:
  validate-pr-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Query PR Labels
        id: query_labels
        run: |
          pr_labels=$(gh pr view ${{ inputs.pull_request_number }} --json labels --jq '.labels[].name' --repo "${{ inputs.repo }}")

          if echo "$pr_labels" | grep -q '^${{ inputs.query_prefix }}'; then
            echo "label_found=true" >> $GITHUB_OUTPUT
          else
            echo "label_found=''" >> $GITHUB_OUTPUT
          fi

      - name: Act on label Presence
        if: ${{ !steps.query_labels.outputs.label_found }}
        run: |
          echo "::error::No label with prefix '${{ inputs.query_prefix }}' found on this PR."
          exit 1

      - name: Act on label Presence
        if: ${{ steps.query_labels.outputs.label_found }}
        run: |
          echo "::notice::Label with prefix '${{ inputs.query_prefix }}' found on this PR."
          exit 0
