name: Verify repository secrets

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      gh_user:
        required: true
      gh_mail:
        required: true

env:
  GH_TOKEN: ${{ secrets.gh_token || false }}
  GH_USER: ${{ secrets.gh_user || false }} 
  GH_EMAIL: ${{ secrets.gh_mail || false }}

jobs:
  verify_secrets:

    runs-on: ubuntu-latest

    # TODO include orgnaistion secrets - needs actions [secrets fine-grained permission](https://docs.github.com/en/rest/actions/secrets?apiVersion=2022-11-28)
    # TODO only check if no inputs provided
    # TODO move verification into github action

    steps:
      - name: 🔎 Verify secret 'GH_TOKEN' for ${{ github.repository }}
        if: ${{ !env.GH_TOKEN }}
        run: |
          echo "::error::Secret 'GH_TOKEN' is not set or empty"

      - name: 🔎 Verify secret 'GH_USER' for ${{ github.repository }}
        if: ${{ !env.GH_USER }}
        run: |
          echo "::error::Secret 'GH_USER' is not set or empty"

      - name: 🔎 Verify secret 'GH_EMAIL' for ${{ github.repository }}
        if: ${{ !env.GH_EMAIL }}
        run: |
          echo "::error::Secret 'GH_EMAIL' is not set or empty"

      - name: 🔎 Secrets verified
        if: ${{ env.GH_TOKEN && env.GH_USER && env.GH_EMAIL }} 
        run: |
          echo "::notice::All required secrets are present."